name       : python-gevent
version    : 21.12.0
release    : 1
source     :
    - https://pypi.io/packages/source/g/gevent/gevent-21.12.0.tar.gz : f48b64578c367b91fa793bf8eaaaf4995cb93c8bc45860e473bf868070ad094e
license    : MIT
component  : programming.python
summary    : Coroutine-based network library
description: |
    gevent is a coroutine -based Python networking library that uses greenlet to provide a high-level synchronous API on top of the libev or libuv event loop.
builddeps  :
    - pkgconfig(python3)
    - dnspython
    - python-greenlet-devel
    - python-psutil
    - python-requests
    - python-zope.event
    - python-zope.interface
rundeps    :
    - python-greenlet
    - python-zope.event
    - python-zope.interface
setup      : |
    cp --verbose $pkgfiles/ignored_tests.txt src/gevent/tests/solus_ignored_tests.txt
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test -m gevent.tests -unone --ignore solus_ignored_tests.txt
    
